CREATE INDEX WISPet$COMPOSITE20 ON WISPet(age)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX WISPet$COMPOSITE21 ON WISPet(birthDay)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX WISPet$COMPOSITE22 ON WISPet(petName)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
